source: src
paths:
  uploads: assets/uploads
  static: ''
  collections: ''
  data: _data
  layouts: _includes
  includes: _includes
collections_config:
  posts:
    path: posts
    output: true
    url: /[slug]/
    _enabled_editors:
      - content
data_config: {}
timezone: Etc/UTC
