backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: dainsaint/dainsaint.com
  # branch: master

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: simple
collections:
  - label: "Blog"
    name: "blog"
    folder: "src/blog"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false}
      - { label: "Color", name: "color", widget: "color", default: "#FFFFFF", required: false }
      - label: "Featured"
        name: "featured"
        widget: "list"
        types:
          - label: Audio
            name: audio
            widget: object
            field: { label: "Audio", name: "audio", widget: file }
          - label: Gallery
            name: gallery
            widget: object
            fields:
              - label: Images
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
          - label: Quote
            name: quote
            widget: object
            field: { label: "Quote", name: "Quote", widget: markdown }
          - label: Youtube
            name: youtube
            widget: object
            field: { label: "Video ID", name: "video_id", widget: string }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Social", name: "social", widget: "image", required: false }
      

  - label: "Posts"
    label_singular: "Post"
    name: "posts"
    folder: "src/posts"
    slug: "{{slug}}"
    create: true
    editor:
      preview: true
    publish: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - { label: "Color", name: "color", widget: "color", default: "#FFFFFF", required: false }
      - label: "Deco"
        name: "deco"
        widget: select
        options: ["almond","birds","camellia","cannabis","cotton","elevation","fountain","gerbera","lighthouse","nightsky","oleander","prunus-sinensis","thistle","tree-of-life"]
      - label: Project
        name: project
        widget: relation
        required: false
        collection: projects
        value_field: "{{slug}}"
        search_fields: ["{{slug}}", "title"]
        display_fields: ["title"]
      - label: "Featured"
        name: "featured"
        widget: "list"
        types:
          - label: Audio
            name: audio
            widget: object
            field: { label: "Audio", name: "audio", widget: file }
          - label: Gallery
            name: gallery
            widget: object
            fields:
              - label: Images
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
          - label: Quote
            name: quote
            widget: object
            field: { label: "Quote", name: "Quote", widget: markdown }
          - label: Youtube
            name: youtube
            widget: object
            field: { label: "Video ID", name: "video_id", widget: string }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Social", name: "social", widget: "image", required: false }

  - label: "Projects"
    label_singular: "Project"
    name: "projects"
    folder: "src/projects"
    slug: "{{slug}}"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Color", name: "color", widget: "color", default: "#FFFFFF", required: false }
      - label: "Featured"
        name: "featured"
        widget: "list"
        types:
          - label: Audio
            name: audio
            widget: object
            field: { label: "Audio", name: "audio", widget: file }
          - label: Gallery
            name: gallery
            widget: object
            fields:
              - label: Images
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
          - label: Quote
            name: quote
            widget: object
            field: { label: "Quote", name: "Quote", widget: markdown }
          - label: Youtube
            name: youtube
            widget: object
            field: { label: "Video ID", name: "video_id", widget: string }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Status", name: "status", widget: "markdown", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Social", name: "social", widget: "image", required: false }


  - label: "Pages"
    label_singular: "Page"
    name: "pages"
    folder: "src/pages"
    slug: "{{slug}}"
    create: true
    editor:
      preview: true
    publish: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Color", name: "color", widget: "color", default: "#FFFFFF", required: false }
      - { label: Hero, name: hero, widget: image, required: false }
      - label: "Featured"
        name: "featured"
        widget: "list"
        types:
          - label: Audio
            name: audio
            widget: object
            field: { label: "Audio", name: "audio", widget: file }
          - label: Gallery
            name: gallery
            widget: object
            fields:
              - label: Images
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
          - label: Quote
            name: quote
            widget: object
            field: { label: "Quote", name: "Quote", widget: markdown }
          - label: Youtube
            name: youtube
            widget: object
            field: { label: "Video ID", name: "video_id", widget: string }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Social", name: "social", widget: "image", required: false }

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Homepage"
        name : "homepage"
        file: "src/index.md"
        fields:
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Promo", name: "promo", widget: "text" }
          - { label: "Social", name: "social", widget: "image" }
          - { label: "Color", name: "color", widget: "color", default: "#FFFFFF", required: false }
          - label: "Featured"
            name: "featured"
            widget: "list"
            types:
              - label: Audio
                name: audio
                widget: object
                field: { label: "Audio", name: "audio", widget: file }
              - label: Gallery
                name: gallery
                widget: object
                fields:
                  - label: Images
                    name: images
                    widget: list
                    field: { label: Image, name: image, widget: image }
              - label: Quote
                name: quote
                widget: object
                field: { label: "Quote", name: "Quote", widget: markdown }
              - label: Youtube
                name: youtube
                widget: object
                field: { label: "Video ID", name: "video_id", widget: string }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          
      - label: "Navigation"
        name : "navigation"
        file: "src/_data/navigation.yml"
        fields:
          - label: Links
            name: links
            widget: list
            fields:
              - label: Page
                name: page
                widget: relation
                collection: pages
                value_field: "{{slug}}"
                search_fields: ["{{slug}}", "title"]
                display_fields: ["title"]
              - { label: URL, name: "url", widget: "string", required: false }